multitenancy:
  tenants:
    - identifier: dukes
      enabled: true
      schema: DUKES
      issuer: http://localhost:8080/realms/dukes
      client-id: edge-service
      client-secret: rocking-secret
    - identifier: beans
      enabled: true
      schema: BEANS
      issuer: http://localhost:8080/realms/beans
      client-id: edge-service
      client-secret: rocking-secret
    - identifier: trixie
      enabled: false
      schema: TRIXIE
      issuer: http://localhost:8080/realms/trixie
      client-id: edge-service
      client-secret: rocking-secret