multitenancy:
  tenants:
    - identifier: dukes
      enabled: true
      client-id: edge-service
      client-secret: rocking-secret
      issuer: http://localhost:8080/realms/dukes
    - identifier: beans
      enabled: true
      client-id: edge-service
      client-secret: rocking-secret
      issuer: http://localhost:8080/realms/beans
    - identifier: trixie
      enabled: false
      client-id: edge-service
      client-secret: rocking-secret
      issuer: http://localhost:8080/realms/trixie